version: 2
jobs:
    build-and-test-docs:
        working_directory: ~/cga-docs
        docker:
            # Python 2 LTS as of 10/18
            - image: circleci/python:2.7.15 
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  # Default pip location is not on circleci's $PATH and cannot be easily added.
                  # Use --user to build to ~/.local/bin
                  command: pip install --user -r requirements.txt
            - run: 
                  name: Install nodejs
                  # Had a hard time persisting ~/.local/bin/mkdocs and others, quickest option was to 
                  # do in the one container :(
                  command: |
                          wget -qO- https://deb.nodesource.com/setup_8.x | sudo -E bash -
                          sudo apt-get install -y nodejs 
            - run:
                  name: Install pa11y
                  command: make pa11y-install
            - run:
                  name: Install broken-links-install
                  command: make broken-links-install
            - run:
                  name: Build mkdocs
                  # Requires Python ~2.7
                  command: ~/.local/bin/mkdocs build 
            - persist_to_workspace:
                  root: ~/cga-docs
                  paths:
                      - site
                      - manifest.yml
    deploy-docs:
        docker:
            - image: govau/cf-cli
        steps:
            - attach_workspace:
                  at: ~/cga-docs
            - run:
                  name: Deploy to cloud.gov.au
                  command: |
                      cd ~/cga-docs
                      cf login -a $CF_API -o $CF_ORG -s $CF_SPACE -u $CF_USER -p $CF_PASSWORD
                      cf zero-downtime-push cgadocs -f manifest.yml --show-app-log
    build-and-test-docs-hugo:
        working_directory: ~/cga-docs
        docker:
            - image: govau/cga-docs:hugo
        steps:
            - checkout
            - run:
                  name: Build theme
                  command: site/themes/designsystem.gov.au/build.sh
            - run: 
                  name: Build site
                  command: cd site && hugo --baseURL https://cgadocs-hugo.apps.y.cld.gov.au/
            - persist_to_workspace:
                  root: ~/cga-docs
                  paths:
                      - site/public
                      - manifest-staging.yml
    deploy-docs-hugo:
        docker:
            - image: govau/cf-cli
        steps:
            - attach_workspace:
                  at: ~/cga-docs
            - run:
                  name: Deploy to staging cloud.gov.au
                  command: |
                      cd ~/cga-docs
                      cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USER -p $CF_PASSWORD_STAGING
                      cf zero-downtime-push cgadocs-hugo -f manifest-staging.yml
workflows:
  version: 2
  build-test-and-deploy:
    jobs: 
      - build-and-test-docs:
          filters:
            branches:
              ignore:
                - hugo
      - deploy-docs:
          requires:
            - build-and-test-docs
          filters:
            branches:
              only:
                - master
          # While working on hugo, deploy its branch to staging.
          # This can be deleted when merged.
      - deploy-docs-staging:
          requires:
            - build-and-test-docs
          filters:
            branches:
              only:
                - hugo
    # While working on hugo, deploy its branch to staging.
    # This can be deleted when merged.
  build-test-and-deploy-hugo:
    jobs:
      - build-and-test-docs-hugo:
          filters:
            branches:
              only:
                - hugo
      - deploy-docs-hugo:
          requires:
            - build-and-test-docs-hugo
          filters:
            branches:
              only:
                - hugo
