version: 2
jobs:
  build-ci:
    working_directory: ~/cga-docs
    docker:
      - image: govau/cga-docs:hugo
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v2-{{ .Branch }}-{{ checksum "site/themes/designsystem.gov.au/src/package-lock.json" }}
      - run:
          name: Build theme
          command: site/themes/designsystem.gov.au/build.sh
      - save_cache:
          paths:
            - site/themes/designsystem.gov.au/src/node_modules
          key: node-v2-{{ .Branch }}-{{ checksum "site/themes/designsystem.gov.au/src/package-lock.json" }}
      - run:
          name: Build site
          command: cd site && hugo --baseURL http://localhost
      - persist_to_workspace:
          root: ~/cga-docs
          paths:
            - .
  create-ci-image:
    machine: true
    working_directory: ~/cga-docs
    steps:
      - attach_workspace:
          at: ~/cga-docs
      - run: |
          docker build . -f .circleci/images/nginx.Dockerfile -t govau/cga-docs:ci-${CIRCLE_SHA1}
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
          docker push govau/cga-docs:ci-${CIRCLE_SHA1}
  test-ci:
    working_directory: ~/cga-docs
    docker:
      - image: circleci/node:9.9.0
      - image: govau/cga-docs:ci-${CIRCLE_SHA1}
    steps:
      - run: curl -i http://localhost
      - run: npm install https://github.com/stevenvachon/broken-link-checker
      - run:
          name: Run broken link checker
          command: |
            node_modules/broken-link-checker/bin/blc \
              --ordered \
              --recursive \
              --follow \
              http://localhost

  build-staging:
      working_directory: ~/cga-docs
      docker:
        - image: govau/cga-docs:hugo
      steps:
        - attach_workspace:
            at: ~/cga-docs
        - run:
            name: Build staging site
            command: cd site && hugo --baseURL https://cgadocs-hugo.apps.y.cld.gov.au
        - persist_to_workspace:
            root: ~/cga-docs
            paths:
              - .
  deploy-staging:
      docker:
        - image: govau/cf-cli
      steps:
        - attach_workspace:
            at: ~/cga-docs
        - run:
            name: Deploy to staging cloud.gov.au
            command: |
              cd ~/cga-docs
              cf login -a $CF_API_STAGING -o $CF_ORG -s $CF_SPACE -u $CF_USER -p $CF_PASSWORD_STAGING
              cf zero-downtime-push cgadocs-hugo -f manifest-staging.yml
workflows:
  version: 2
  do-it:
    jobs:
      - build-ci
      - create-ci-image:
          requires:
            - build-ci
      - test-ci:
          requires:
            - create-ci-image
      - build-staging:
          requires:
            - test-ci
      - deploy-staging:
          requires:
            - build-staging
          filters:
            branches:
              only:
                - hugo # change to master when finished
